### ISSUE TITLE
Show incremental file size increases with images -t 

### ISSUE THREAD

**Issue by hsingh23** [justone/dockviz#14]
I'm more interested in seeing how much new stuff is added in each layer then the total size of the current layer with the previous ones. Could there be an option for this in the images command? What do you think?

**Comment by justone** [comment]
I think that sounds like a good idea.  Perhaps `--incremental` or `-i`.

**Comment by justone** [comment]
Added in master, will be in next release.

**Comment by hsingh23** [comment]
Woot!


Peace

Harsh Singh

**Comment by asymmetric** [comment]
Has the feature been released already? If I pass the `-i` flag I still see cumulative sizes.

**Comment by justone** [comment]
Yes, it was released as part of version 0.3. `dockviz --version` will show which one you're running.

**Comment by justone** [comment]
I was looking into this again, and it looks like docker 1.10 now reports both size and virtualsize as the same amount.

https://gist.github.com/justone/933cd36d92f763bfb45c

**Comment by asymmetric** [comment]
Good catch! As a matter of fact, I'm running 1.10
