### ISSUE TITLE
--privileged needed

### ISSUE THREAD

**Issue by jhgoebbert** [justone/dockviz#17]
I have to use --privileged to make dockviz run
docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz containers
You might want to add that information to your documentation.

If I do not use --privileged I get the error:
Unable to access Docker socket, please run like this:
  docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz containers <args>
For more help, run 'dockviz help'

even though my user is part of the 'docker' group and /var/run/docker.sock is readable/writeable for docker group:
srw-rw----. 1 root docker 0 Feb 25 13:11 /var/run/docker.sock

The problem might be related to SELinux.

P.S: thanks for dockviz ... it is a great tool !!!!

**Comment by justone** [comment]
Thanks for the report.  I am planning on adding some text to the help output.

And, as was mentioned in #12, [this repo](https://github.com/dpw/selinux-dockersock) is an alternative fix to using the `--privileged` flag.

**Comment by justone** [comment]
This is a part of the latest release, [v0.4.2](https://github.com/justone/dockviz/releases/tag/v0.4.2).

Thanks.
