### ISSUE TITLE
With Docker 1.10 dockviz don't see intermediate images

### ISSUE THREAD

**Issue by vektory79** [justone/dockviz#20]
With Docker 1.10 dockviz don't see intermediate images. dockviz shows an explicitly pulled images only:

    vektor@vektor-lx:/$ dockviz images -t
    ├─sha256:dd5cc Virtual Size: 652.9 MB Tags: maven:latest
    ├─sha256:2d310 Virtual Size: 539.7 MB Tags: openshift/origin:latest
    ├─sha256:97434 Virtual Size: 188.0 MB Tags: ubuntu:latest
    ├─sha256:a0d4a Virtual Size: 188.0 MB Tags: ubuntu:14.04
    ├─sha256:3668e Virtual Size: 5.9 MB Tags: nate/dockviz:latest
    ├─sha256:6fae6 Virtual Size: 348.8 MB Tags: training/webapp:latest
    └─sha256:49d95 Virtual Size: 447.0 MB Tags: training/sinatra:latest
      └─sha256:957f5 Virtual Size: 452.5 MB Tags: vektor/sinatra:v2

**Comment by justone** [comment]
Indeed.  It has to do with the switch to content-addressable images that 1.10 brought.  I'm working on figuring out how to restore the functionality.  It will probably involve a pull request to docker itself.

**Comment by justone** [comment]
Getting closer to solving this issue.  Thank you for your patience.

**Comment by justone** [comment]
Sorry to miss closing this out, but with the [v0.4 release](https://github.com/justone/dockviz/releases/tag/v0.4) of dockviz, intermediate images should show up again.
