### ISSUE TITLE
Doesn't work after upgrade to 1.11.0

### ISSUE THREAD

**Issue by IIIEII** [justone/dockviz#21]
After upgrading my docker-machine to version 1.11.0 dockviz returns error:
$ dockviz images -t
Error reading JSON: %!(EXTRA *json.SyntaxError=unexpected end of JSON input)

My system information:
$ docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 58
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 59
 Dirperm1 Supported: true
Logging Driver: json-file
Plugins: 
 Volume: cifs local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.79 GiB
Name: default
ID: IP3A:ADCB:FJOB:CCLX:MOND:AZLI:O6B5:DVAN:BZJO:T4SL:RPC4:CTDT
Debug mode (server): true
 File Descriptors: 31
 Goroutines: 63
 System Time: 2016-04-19T08:14:08.553994959Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: 
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by justone** [comment]
Thanks for reporting this.  It looks like docker 1.11.0 is a little more strict about not opening stdin if not requested.  The solution is to add `-it` to your dockviz alias, like this:

```
alias dockviz="docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz"
```

I updated the project README.md to reflect this as well.

**Comment by IIIEII** [comment]
Thank you! Now it works again.

**Comment by jonathanperret** [comment]
I just stumbled upon this as well. Unfortunately `-it` is not an option when you're running dockviz in a non-TTY environment (my use case is inside a Jenkins job).

I tried to understand which part of dockviz required opening stdin but my golang-fu is too weak.

Btw thanks for dockviz, it's a neat little tool I use very regularly!

**Comment by justone** [comment]
Ah, sorry about that.  The stdin mode of dockviz is an old mode and I'll probably rip it out or put it behind a command line flag at some point.

Glad that dockviz is useful.

**Comment by alevinetx** [comment]
I'm a little late to the game with this issue, but i'm experiencing the same thing re: interactive not playing well with Jenkins processes.   Was there any progress made on the removal of the stdin?   I, too, don't know go, so I can't fix it myself.

 Thanks for this tool, btw!

**Comment by justone** [comment]
I think it's finally time to remove stdin support.  I created a new issue (#31) for it.
