### ISSUE TITLE
Image IDs differ when using --tree vs --dot

### ISSUE THREAD

**Issue by kevin-canadian** [justone/dockviz#24]
When running using --tree the ID is "missing" for images without a hash, and "sha1:hash" for images with a hash.  When running using --dot all images contain the "synth:fake" value.

I think it would be best if both --tree and --dot produced the same output.  Moreover, this output should match the output from docker images when possible.  In other words, whenever a hash is available, it should be without a prefix and it should use the first 12 characters of the sha hash (unless the -n option is used).  When a hash is not available, both should provide the same (either "missing", or better yet, the "synth:fake" value).

**Comment by justone** [comment]
Thanks for catching that, will do a release soon.

**Comment by kevin-canadian** [comment]
Great, thanks for the quick resolution!

**Comment by kevin-canadian** [comment]
Just tested this, and it's better.  But the IDs provided via the --tree option still have a "sha256:" prefix.  Do you think you could remove this?  Again, ideally this ID should match the output from "docker images", which is the ID that we need to use with other docker commands (e.g. docker rmi <ID>).

**Comment by justone** [comment]
Good point, just added a commit to do that.  I tried to match up with `docker images` way of doing things.

Incidentally, you can pass in the image names with the `sha256:` prefix and docker images will do the right thing.

**Comment by justone** [comment]
This is a part of the latest release, [v0.4.2](https://github.com/justone/dockviz/releases/tag/v0.4.2).

Thanks.

**Comment by kevin-canadian** [comment]
I wasn't sure if the prefix was allowed in other docker commands, but it's definitely nicer if the outputs match.  Thank you, again!
