### ISSUE TITLE
Error reading JSON: %!(EXTRA *json.SyntaxError=unexpected end of JSON input)

### ISSUE THREAD

**Issue by dimonf** [justone/dockviz#27]
It seems that I am the only user who has this problem: search for report of similar simpthom on internet was unsuccessful so far. Any idea how to get closer to the cause of the error?

docker info

Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 125
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.35 GiB
Name: XXX
ID: XXX
Docker Root Dir: /data/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Comment by justone** [comment]
I usually see this error when `-it` isn't used when running dockviz as a docker image. `-it` is required as of docker version 1.10. 

Let me know if this fixes the issue.

**Comment by dimonf** [comment]
Yep, that is the cure. You've made my day, thank you.

**Comment by flacoman91** [comment]
Hi, 

I am going through an old training video through pluralsight and they keep referencing the --tree command. ARGH.

So I'm trying dockviz.

I'm getting this same error.  

I am running ubuntu 16.04
docker version shows 1.11.2 for both server and client

the -it flag does not work for me. and I am getting that Error Reading JSON message. 

I am running the command
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -it

**Comment by justone** [comment]
Hey @flacoman91, looks like the issue with your command is where the `-it` is placed.  It is an option on the docker run command, not dockviz itself..  Here's the command that will work for you:

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t`

**Comment by flacoman91** [comment]
Ah thanks @justone  that works. and thank you for being so responsive.

**Comment by justone** [comment]
No problem, glad it worked out.
