### ISSUE TITLE
Remove stdin support or put it behind a flag

### ISSUE THREAD

**Issue by justone** [justone/dockviz#31]
Stdin mode is an old way of running `dockviz` and it's now causing issues (like #21).

It should be removed or put behind a flag.

**Comment by alevinetx** [comment]
Do you have a sense of when you expect to be done with this ticket? a week, a month?   Appreciate it. :)

**Comment by justone** [comment]
I just updated the code and cut a new release ([v0.5.0](https://github.com/justone/dockviz/releases/tag/v0.5.0)).  Try it out and let me know if it fixes your issue.

**Comment by alevinetx** [comment]
I don't see it up on dockerhub yet. when it appears, i'll give it a shot.  thanks for that quick response !

**Comment by justone** [comment]
Ah cool. Didn't get a chance to update the docker image yet.

**Comment by alevinetx** [comment]
works great, mate!   

thank you again!!

**Comment by alevinetx** [comment]
Sorry for posting on this closed issue, but I'm not sure how else to ask/send you a message.  I want to make sure I'm using this tool properly.     Assuming I have 2 images,  base and compound, where compound is built upon base.   If I run dockviz against base, I see the diagram down to compound.  However, if I run dockviz against compound, the only item that appears is compound.  Is there a way to force an upward tree from an image, to see its hierarchy?    

thanks!

**Comment by justone** [comment]
No worries. Best thing would be to create a new issue with your question and as much information as you can about it. Command output, dockerfiles, etc.

Could you do that with your question?

**Comment by justone** [comment]
@alevinetx the docker hub image has been updated.
