### ISSUE TITLE
FRQ: display the build command of each layer

### ISSUE THREAD

**Issue by missedone** [justone/dockviz#35]
hey, for now `dockviz images -t` just show the layer id and virtual size, i'd like to see the corresponding build command of that layer as well. (probably we can introduce a new flag for this).
thx

**Comment by justone** [comment]
I just released [v0.6.0](https://github.com/justone/dockviz/releases/tag/v0.6.0), which includes a `--show-created-by` flag which should do what you need.

Let me know if you have any difficulty with it.
