### ISSUE TITLE
0.6.0 reports itself as 0.5.0

### ISSUE THREAD

**Issue by ilovezfs** [justone/dockviz#40]
https://github.com/justone/dockviz/blob/master/cli.go#L23

**Comment by justone** [comment]
Thank you for catching this, I'll do another release soon.

**Comment by justone** [comment]
I just released [v0.6.1](https://github.com/justone/dockviz/releases/tag/v0.6.1).

**Comment by ilovezfs** [comment]
Thanks @justone! Voilà https://github.com/Homebrew/homebrew-core/pull/26826

**Comment by justone** [comment]
Wow, thank you too @ilovezfs!
