### ISSUE TITLE
Go vendoring?

### ISSUE THREAD

**Issue by ilovezfs** [justone/dockviz#41]
Ref: https://github.com/Homebrew/homebrew-core/issues/21801

@justone Would you be willing to start using a Go `vendor` directory or one of the other Go vendor systems so that we can avoid Go resource blocks in the Homebrew formula for `dockviz`?

Currently, the `dockviz` formula has four Go resource blocks. Checking whether there are updates for any, all, or none of these resources, and whether any new ones need to be added, every time `dockviz` is upgraded is not ideal, but In the absence of Go vendoring, this is the only way we can ensure reproducible builds.

Some good choices are
https://github.com/golang/dep (`dep ensure`)
https://github.com/Masterminds/glide (`glide install`)
https://github.com/kardianos/govendor (`govendor sync`)
https://github.com/tools/godep (`godep restore`)

**Comment by justone** [comment]
Yes, I definitely want to start using vendoring.  Dockviz dates from the 1.4 days of Go, and so I haven't ever updated it.  I do have other projects that use govendor, so I'll switch over to that when I get a chance.

**Comment by ilovezfs** [comment]
Awesome! Thanks @justone! See https://github.com/Homebrew/homebrew-core/pull/26862.

>Another option for installing on mac is to just download the binary. I always build one with a checksum for each release.

Everything in https://github.com/Homebrew/homebrew-core is required to build from source, and then we distribute the prebuilt binary "bottles" that get built by our CI.
