### ISSUE TITLE
improve the help in cli to indicate pass the /var/run/docker.sock 

### ISSUE THREAD

**Issue by larrycai** [justone/dockviz#9]
I already pull the `nate/dockviz`, and am used to forget the complete command to run it like

    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t

Will be nice to give hints or help when I just type 

    docker run nate/dockviz
    docker run nate/dockviz image

Like the output

    docker@boot2docker:~$ docker run --rm nate/dockviz images
    dial unix /var/run/docker.sock: no such file or directory
    you may want to try docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz images -t

Or simple add `help` for this besides `image` and `container`

Then as end user, I don't need to google to have complete command line

**Comment by justone** [comment]
I just released a new version of dockviz, so if you `docker pull nate/dockviz` and run it again there will be a helpful error message.  I also added a help subcommand.

Thanks.
